### PR TITLE
typescript rewrite

### LINKED ISSUE #3: Rewrite in TypeScript
snyowwax-san >w< does nyot wike *screams* my javascwipt code :(

### PR DESCRIPTION
**Pull request by EmeraldSnorlax**
fixes #3

### CODE REVIEW

**Comment by sourTaste000** [comment]
:pray:

**Comment by d1snin** [comment]
:pray:

**Comment by sourTaste000** [comment]
wtf is this how??

**Comment by EmeraldSnorlax** [comment]
can you fuckers not spam threads with useless shit holy fuck

**Pull request closed without merging**
